### ISSUE TITLE
Error in atkinson dithering

### ISSUE THREAD

**Issue by AljoschaMeyer** [dpiccone/ditherjs#3]
Unless I'm misunderstanding the code, the error diffusion always adds the error of the red channel, even to the green and blue one.

**Comment by robisodd** [comment]
Yep, I noticed that, too.  All the "q[r]" from lines 162-174 should be "q[g]" and "q[b]", respectively.  Modified it on mine and it looks much better.

**Comment by dpiccone** [comment]
Thanks for catching this! I have fixed it with v0.3
